#ifndef TUI_DEBUG_H
#define TUI_DEBUG_H

/* Warning, this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define DEFAULT_REPLAY_PORT 50505

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Return the most recent error message, or an empty string when none is set.
//
// The returned pointer is valid until the next call into the tui-debug C API
// on any thread.
const char *tui_debug_last_error(void);

// After a successful launch, call [`tui_debug_sync_snapshot`] once to obtain
// the stop-on-entry snapshot captured during initialization.
void *tui_debug_session_launch(const char *program, const char *args_json);

// Launch a native binary debug session via lldb-dap.
void *tui_debug_session_launch_lldb(const char *program, const char *args_json);

// Launch a native binary debug session via rr record + replay (reverse debugging).
void *tui_debug_session_launch_rr(const char *program, const char *args_json);

// Free a session created by [`tui_debug_session_launch`].
void tui_debug_session_free(void *session);

// Poll for the next session event.
//
// Writes JSON into `json_out` when an event is available.
//
// Returns `0` on success, `1` when no event is ready, and `-1` on error.
int tui_debug_poll(void *session, char *json_out, size_t cap);

// Execute a debugger command described as JSON, e.g. `{"op":"continue"}`.
int tui_debug_command(void *session, const char *cmd_json);

// Refresh debugger state and write a snapshot as JSON into `json_out`.
//
// Returns the cached stop-on-entry snapshot from launch when still available,
// otherwise fetches a fresh snapshot from the debug adapter.
//
// JSON shape: `{"type":"snapshot","snapshot":{...}}`
//
// Returns `0` on success and `-1` on error.
int tui_debug_sync_snapshot(void *session, char *json_out, size_t cap);

// Drain buffered program console output into `json_out` as a JSON array.
//
// Each entry has `category` and `text` fields.
//
// Returns `0` on success and `-1` on error.
int tui_debug_drain_console(void *session, char *json_out, size_t cap);

// Write raw bytes to the debuggee stdin (integrated terminal PTY).
//
// Returns `0` on success and `-1` on error.
int tui_debug_terminal_write(void *session, const uint8_t *bytes, size_t len);

// Evaluate an expression in the given stack frame.
//
// `context` is typically `"repl"` or `"watch"`. Result is written to `result_out`.
//
// Returns `0` on success and `-1` on error.
int tui_debug_evaluate(void *session,
                       const char *expression,
                       int64_t frame_id,
                       const char *context,
                       char *result_out,
                       size_t cap);

// Request REPL completions for `text` at `column` (1-based) in `frame_id`.
//
// On success, writes a JSON array of completion items to `result_out`.
//
// Returns `0` on success and `-1` on error.
int tui_debug_completions(void *session,
                          const char *text,
                          int64_t column,
                          int64_t frame_id,
                          char *result_out,
                          size_t cap);

// Set breakpoints for `path`. `lines_json` is a JSON array of line numbers (`[1,5]`) or
// breakpoint objects (`[{"line":24,"condition":"x > 1","hitCondition":">= 5"}]`).
// On success, writes adapter results to `results_out` as
// `[{"line":24,"verified":true,"hitCount":3}]` when `results_out` is non-null.
int tui_debug_set_breakpoints(void *session,
                              const char *path,
                              const char *lines_json,
                              char *results_out,
                              size_t results_cap);

// Resolve a variable to a DAP `dataId` for `setDataBreakpoints`.
// Writes `{"dataId":"...","description":"...","accessTypes":["write"]}` to `json_out`.
int tui_debug_data_breakpoint_info(void *session,
                                   int64_t variables_reference,
                                   int64_t frame_id,
                                   const char *name,
                                   char *json_out,
                                   size_t cap);

// Replace all function breakpoints. `breakpoints_json` is a JSON array of
// `{"name":"main","condition":"...","hitCondition":"..."}`.
// On success, writes adapter results to `results_out` when non-null.
int tui_debug_set_function_breakpoints(void *session,
                                       const char *breakpoints_json,
                                       char *results_out,
                                       size_t results_cap);

// Enable exception breakpoint filters. `filters_json` is a JSON array of filter ids
// (`["uncaught","raised"]`) or objects (`[{"filter":"cxx-throw","condition":"std::runtime_error"}]`).
int tui_debug_set_exception_breakpoints(void *session,
                                        const char *filters_json);

// Replace all data breakpoints. `breakpoints_json` is a JSON array of
// `{"dataId":"...","description":"x","accessType":"write","condition":"..."}`.
// On success, writes adapter results to `results_out` when non-null.
int tui_debug_set_data_breakpoints(void *session,
                                   const char *breakpoints_json,
                                   char *results_out,
                                   size_t results_cap);

// Fetch variables for a DAP `variablesReference` into `json_out` as a JSON array.
int tui_debug_fetch_variables(void *session,
                              int64_t variables_reference,
                              const char *scope_name,
                              char *json_out,
                              size_t cap);

// Set a variable value in the given scope (`variablesReference`).
int tui_debug_set_variable(void *session,
                           int64_t variables_reference,
                           const char *name,
                           const char *value,
                           char *result_out,
                           size_t cap);

// Fetch source text for a DAP `sourceReference` into `source_out`.
int tui_debug_fetch_source(void *session, int64_t source_reference, char *source_out, size_t cap);

// Fetch possible step-in targets for a stack frame into `json_out` as a JSON array.
int tui_debug_fetch_step_in_targets(void *session, int64_t frame_id, char *json_out, size_t cap);

// Fetch possible goto targets for a source location into `json_out` as a JSON array.
int tui_debug_fetch_goto_targets(void *session,
                                 const char *path,
                                 int64_t line,
                                 int64_t column,
                                 int64_t source_reference,
                                 char *json_out,
                                 size_t cap);

// Initialize tree-sitter grammars (built-in Python + optional external `.so` files).
//
// Safe to call multiple times; initialization runs once per process.
void tui_debug_init(void);

// Returns `1` when a grammar for `language` is loaded, otherwise `0`.
int32_t tui_debug_language_is_loaded(const char *language);

// Try to load a grammar from `DAP_TREE_SITTER_DIR/<language>/`.
//
// Returns `0` on success, `-1` on error (see [`tui_debug_last_error`]).
int32_t tui_debug_try_load_language(const char *language);

// Highlight a source viewport and write JSON to `json_out`.
//
// Returns `0` on success, `-1` on error. JSON schema:
// `[{"line":1,"spans":[{"text":"def","kind":"keyword"}]}]`
int32_t tui_debug_highlight_viewport(const char *language,
                                     const char *source,
                                     int64_t first_line,
                                     int64_t line_count,
                                     char *json_out,
                                     size_t cap);

// Resolve a function name on `line` (1-based) using tree-sitter when the grammar is loaded.
//
// Returns `0` when a name was written to `name_out`, `1` when no function was found,
// and `-1` on error (see [`tui_debug_last_error`]).
int32_t tui_debug_function_name_at_line(const char *language,
                                        const char *source,
                                        uint32_t line,
                                        char *name_out,
                                        size_t name_cap);

// Find the first definition line (1-based) of `name` using tree-sitter.
//
// Returns `0` when `line_out` was set, `1` when not found, and `-1` on error.
int32_t tui_debug_function_definition_line(const char *language,
                                           const char *source,
                                           const char *name,
                                           uint32_t *line_out);

// Resolve a watch expression at `line` (1-based) and `byte_column` (UTF-8 byte offset in the line).
//
// Returns `0` when `expression_out` was written. When the position refers to a simple identifier,
// `simple_out` receives the same name (for data breakpoints on locals). Returns `1` when nothing
// was found and `-1` on error.
int32_t tui_debug_identifier_at_position(const char *language,
                                         const char *source,
                                         uint32_t line,
                                         uint32_t byte_column,
                                         char *expression_out,
                                         size_t expression_cap,
                                         char *simple_out,
                                         size_t simple_cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TUI_DEBUG_H */
