#ifndef TUI_DEBUG_H
#define TUI_DEBUG_H

/* Warning, this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *tui_debug_last_error(void);

void *tui_debug_session_launch(const char *program);

void tui_debug_session_free(void *session);

int tui_debug_poll(void *session, char *json_out, size_t cap);

int tui_debug_command(void *session, const char *cmd_json);

int tui_debug_sync_snapshot(void *session, char *json_out, size_t cap);

int tui_debug_drain_console(void *session, char *json_out, size_t cap);

int tui_debug_evaluate(void *session,
                       const char *expression,
                       int64_t frame_id,
                       const char *context,
                       char *result_out,
                       size_t cap);

int tui_debug_set_breakpoints(void *session, const char *path, const char *lines_json);

int tui_debug_fetch_variables(void *session,
                              int64_t variables_reference,
                              char *json_out,
                              size_t cap);

int32_t tui_debug_highlight_viewport(const char *language,
                                     const char *source,
                                     int64_t first_line,
                                     int64_t line_count,
                                     char *json_out,
                                     size_t cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TUI_DEBUG_H */
